In [1]:
import torch

In [2]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[1,2],[3,4]])

In [3]:
x

tensor([[1, 2],
        [3, 4]])

In [4]:
y

tensor([[1, 2],
        [3, 4]])

In [5]:
def MatrixMul(x,y):
    if x.shape[1] == y.shape[0]:
        z= torch.zeros(x.shape[0],y.shape[1])
        for i in range(len(x)):
            for j in range(len(y[0])):
                for k in range(len(y)):
                    z[i][j] += x[i][k] * y[k][j] 
        return z
    
    else:
        return "null"

In [6]:
z = MatrixMul(x,y)
if z == "null":
    print("Matrix Multiplication not Possible")
else:
    print(z)

tensor([[ 7., 10.],
        [15., 22.]])
